training:
  train_batch_size: 40
  test_batch_size: 128
  threshold: 0.88134765625
  num_workers: 2
  pin_memory: true
  epochs: 50
  map_bins: 50 #Set to null to disable

  learning_rate: 0.001
  weight_decay: 0.0001
  seed: 42

inference:
  batch_size: 128
  threshold: 0.5
  num_workers: 2
  pin_memory: true
  map_bins: null
  

data:
  deduplicate: false
  max_sequence_length: .inf
 

logging:
  log_interval: 10
  save_model: true
  checkpoint_dir: "checkpoints/"
  tensorboard: true
  tensorboard_dir: "logs/"


paths: #Default paths. Can be modified by script args.
  data: "data/"
  outputs: "outputs/"
  parenthood_2019: "data/parenthood/parenthood_jul_2019.json"
  parenthood_2024: "data/parenthood/parenthood_jul_2024.json"

wandb:
  project: "protein-functions"
  entity: "proteinfertorch"
  name: "proteinfertorch"

base_architecture:
  input_dim: 20
  output_embedding_dim: 1100
  kernel_size: 9
  dilation_base: 3
  num_resnet_blocks: 5
  bottleneck_factor: 0.5
  activation: "relu"

go_random_defaults:
  output_dim: 32102 # equal to the number of unique labels
  threshold: 0.88134765625 #0.710102

go_clustered_defaults:
  output_dim: 32101 # equal to the number of unique labels
  threshold: 0.88134765625 #TODO: TBD

ec_random_defaults:
  output_dim: 5134 # equal to the number of unique labels
  threshold: 0.88134765625 #TODO: TBD

ec_clustered_defaults:
  output_dim: 5134 # equal to the number of unique labels
  threshold: 0.88134765625 #TODO: TBD

go_defaults:
  input_dim: 20
  output_embedding_dim: 1100
  output_dim: 32102 # equal to the number of unique labels
  kernel_size: 9
  dilation_base: 3
  num_resnet_blocks: 5
  bottleneck_factor: 0.5
  activation: "relu"
  threshold: 0.88134765625 #0.710102
  
ec_defaults:
  input_dim: 20
  output_embedding_dim: 1100
  output_dim: 5134 # equal to the number of unique labels
  kernel_size: 9
  dilation_base: 3
  num_resnet_blocks: 5
  bottleneck_factor: 0.5
  activation: "relu"
  threshold: 0.710102